const STORAGE_KEY = "puter-ai-chat-history-v1";
const state = { messages: [], busy: false };
const els = { messages:document.getElementById("messages"), form:document.getElementById("chatForm"), input:document.getElementById("promptInput"), send:document.getElementById("sendBtn"), newChat:document.getElementById("newChatBtn"), clear:document.getElementById("clearBtn"), model:document.getElementById("modelSelect"), title:document.getElementById("chatTitle"), suggestions:document.getElementById("suggestions") };
function saveHistory(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.messages));}
function loadHistory(){try{const raw=localStorage.getItem(STORAGE_KEY);state.messages=raw?JSON.parse(raw):[]}catch{state.messages=[]}}
function render(){if(!state.messages.length){els.messages.innerHTML='<div class="empty"><div class="empty-card"><h3>How can I help?</h3><p>Ask a question, explain a concept, brainstorm an idea, or paste code to debug. Responses stream directly from Puter.js.</p></div></div>';els.title.textContent="New conversation";return}els.title.textContent=state.messages[0]?.role==="user"?state.messages[0].content.slice(0,42)||"Conversation":"Conversation";els.messages.innerHTML="";for(const msg of state.messages){const row=document.createElement("div");row.className=`message-row ${msg.role}`;const bubble=document.createElement("div");bubble.className=`message ${msg.role}`;const meta=document.createElement("div");meta.className="message-meta";meta.textContent=msg.role==="user"?"You":"AI";const body=document.createElement("div");body.textContent=String(msg.content||"");bubble.append(meta,body);row.appendChild(bubble);els.messages.appendChild(row)}els.messages.scrollTop=els.messages.scrollHeight}
function setBusy(value){state.busy=value;els.send.disabled=value;els.input.disabled=value;els.model.disabled=value}
function appendAssistantPlaceholder(){const row=document.createElement("div");row.className="message-row assistant";const bubble=document.createElement("div");bubble.className="message assistant";const meta=document.createElement("div");meta.className="message-meta";meta.textContent="AI";const body=document.createElement("div");body.innerHTML='<span class="typing"><span></span><span></span><span></span></span>';bubble.append(meta,body);row.appendChild(bubble);els.messages.appendChild(row);els.messages.scrollTop=els.messages.scrollHeight;return body}
async function sendMessage(text){if(!text||state.busy)return;state.messages.push({role:"user",content:text});saveHistory();render();const body=appendAssistantPlaceholder();setBusy(true);try{const messages=[{role:"system",content:"You are a helpful, concise AI assistant. Use clear formatting and practical explanations."},...state.messages];const response=await puter.ai.chat(messages,{model:els.model.value,stream:true});let accumulated="";for await(const part of response){if(part?.type==="error")throw new Error(part.error?.message||"The AI provider returned an error.");const chunk=part?.text??"";if(chunk){accumulated+=chunk;body.textContent=accumulated;els.messages.scrollTop=els.messages.scrollHeight}}if(!accumulated.trim())accumulated="I didn't receive any text from the model.";state.messages.push({role:"assistant",content:accumulated});saveHistory();render()}catch(error){body.textContent=`Error: ${error?.message||"Something went wrong while contacting Puter AI."}`}finally{setBusy(false);els.input.focus()}}
els.form.addEventListener("submit",async e=>{e.preventDefault();const text=els.input.value.trim();if(!text)return;els.input.value="";autoResize();await sendMessage(text)});
els.input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();els.form.requestSubmit()}});els.input.addEventListener("input",autoResize);
function autoResize(){els.input.style.height="auto";els.input.style.height=Math.min(els.input.scrollHeight,180)+"px"}
els.newChat.addEventListener("click",()=>{state.messages=[];saveHistory();render();els.input.value="";els.input.focus()});els.clear.addEventListener("click",()=>{state.messages=[];saveHistory();render()});els.suggestions.addEventListener("click",e=>{const btn=e.target.closest("button[data-prompt]");if(!btn||state.busy)return;els.input.value=btn.dataset.prompt;autoResize();els.form.requestSubmit()});loadHistory();render();autoResize();
