const STORAGE_KEY = "puter-ai-chat-history-v2";
const state = { messages: [], busy: false };
const els = { messages:document.getElementById("messages"), form:document.getElementById("chatForm"), input:document.getElementById("promptInput"), send:document.getElementById("sendBtn"), newChat:document.getElementById("newChatBtn"), clear:document.getElementById("clearBtn"), model:document.getElementById("modelSelect"), title:document.getElementById("chatTitle"), suggestions:document.getElementById("suggestions") };

marked.setOptions({gfm:true,breaks:true});

function saveHistory(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.messages));}
function loadHistory(){try{const raw=localStorage.getItem(STORAGE_KEY);state.messages=raw?JSON.parse(raw):[]}catch{state.messages=[]}}
function safeMarkdown(text){return DOMPurify.sanitize(marked.parse(String(text||"")),{USE_PROFILES:{html:true}})}
function renderMarkdown(text){const html=safeMarkdown(text);const holder=document.createElement("div");holder.innerHTML=html;holder.className="markdown";holder.querySelectorAll("pre code").forEach(code=>{const pre=code.parentElement;const lang=(code.className.match(/language-([\w-]+)/)||[])[1]||"text";try{if(lang!=="text")hljs.highlightElement(code)}catch{}const wrap=document.createElement("div");wrap.className="code-wrap";const head=document.createElement("div");head.className="code-head";const label=document.createElement("span");label.textContent=lang;const copy=document.createElement("button");copy.className="copy-code";copy.type="button";copy.textContent="Copy";copy.dataset.code=code.textContent;head.append(label,copy);pre.parentNode.insertBefore(wrap,pre);wrap.append(head,pre)});return holder}
function makeAnswerBody(content){const body=document.createElement("div");body.className="message-body";body.appendChild(renderMarkdown(content));return body}
function render(){if(!state.messages.length){els.messages.innerHTML='<div class="empty"><div class="empty-card"><div class="empty-logo">✦</div><h3>How can I help?</h3><p>Ask anything. Responses are rendered as clean Markdown with headings, lists, tables, quotes, links, and syntax-highlighted code.</p></div></div>';els.title.textContent="New conversation";return}els.title.textContent=state.messages[0]?.role==="user"?state.messages[0].content.slice(0,42)||"Conversation":"Conversation";els.messages.innerHTML="";for(const msg of state.messages){const row=document.createElement("div");row.className=`message-row ${msg.role}`;const bubble=document.createElement("div");bubble.className=`message ${msg.role}`;const meta=document.createElement("div");meta.className="message-meta";meta.textContent=msg.role==="user"?"You":"AI";bubble.appendChild(meta);if(msg.role==="assistant"){bubble.appendChild(makeAnswerBody(msg.content));const actions=document.createElement("div");actions.className="answer-actions";const copy=document.createElement("button");copy.className="copy-answer";copy.type="button";copy.textContent="Copy";copy.dataset.answer=msg.content;actions.appendChild(copy);bubble.appendChild(actions)}else{const body=document.createElement("div");body.className="message-body";body.textContent=msg.content;bubble.appendChild(body)}row.appendChild(bubble);els.messages.appendChild(row)}els.messages.scrollTop=els.messages.scrollHeight}
function setBusy(value){state.busy=value;els.send.disabled=value;els.input.disabled=value;els.model.disabled=value;els.send.querySelector("span").textContent=value?"Thinking":"Send"}
function appendAssistantPlaceholder(){const row=document.createElement("div");row.className="message-row assistant";const bubble=document.createElement("div");bubble.className="message assistant";const meta=document.createElement("div");meta.className="message-meta";meta.textContent="AI";const body=document.createElement("div");body.className="message-body";body.innerHTML='<span class="typing"><span></span><span></span><span></span></span>';bubble.append(meta,body);row.appendChild(bubble);els.messages.appendChild(row);els.messages.scrollTop=els.messages.scrollHeight;return body}
function updateStreamingBody(body,text){body.replaceChildren(renderMarkdown(text));els.messages.scrollTop=els.messages.scrollHeight}
async function sendMessage(text){if(!text||state.busy)return;state.messages.push({role:"user",content:text});saveHistory();render();const body=appendAssistantPlaceholder();setBusy(true);try{const messages=[{role:"system",content:"You are a helpful AI assistant. Always answer using well-structured Markdown when formatting improves clarity. Use headings for sections, bullet or numbered lists for steps, Markdown tables for comparisons, blockquotes for important notes, inline code for identifiers, and fenced code blocks with a language label for code. Keep formatting readable and do not wrap the entire response in a code block."},...state.messages];const response=await puter.ai.chat(messages,{model:els.model.value,stream:true});let accumulated="";for await(const part of response){if(part?.type==="error")throw new Error(part.error?.message||"The AI provider returned an error.");const chunk=part?.text??"";if(chunk){accumulated+=chunk;updateStreamingBody(body,accumulated)}}if(!accumulated.trim())accumulated="I didn't receive any text from the model.";state.messages.push({role:"assistant",content:accumulated});saveHistory();render()}catch(error){body.textContent=`Error: ${error?.message||"Something went wrong while contacting Puter AI."}`}finally{setBusy(false);els.input.focus()}}
els.form.addEventListener("submit",async e=>{e.preventDefault();const text=els.input.value.trim();if(!text)return;els.input.value="";autoResize();await sendMessage(text)});
els.input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();els.form.requestSubmit()}});els.input.addEventListener("input",autoResize);
function autoResize(){els.input.style.height="auto";els.input.style.height=Math.min(els.input.scrollHeight,180)+"px"}
els.newChat.addEventListener("click",()=>{state.messages=[];saveHistory();render();els.input.value="";els.input.focus()});els.clear.addEventListener("click",()=>{state.messages=[];saveHistory();render();els.input.focus()});els.suggestions.addEventListener("click",e=>{const btn=e.target.closest("button[data-prompt]");if(!btn||state.busy)return;els.input.value=btn.dataset.prompt;autoResize();els.form.requestSubmit()});
els.messages.addEventListener("click",async e=>{const codeBtn=e.target.closest(".copy-code");const answerBtn=e.target.closest(".copy-answer");if(codeBtn){await navigator.clipboard.writeText(codeBtn.dataset.code||"");codeBtn.textContent="Copied";setTimeout(()=>codeBtn.textContent="Copy",1200)}if(answerBtn){await navigator.clipboard.writeText(answerBtn.dataset.answer||"");answerBtn.textContent="Copied";setTimeout(()=>answerBtn.textContent="Copy",1200)}});
loadHistory();render();autoResize();
